@extends('layouts.app')
@section('header')
    @include('blocks.header.header')
@endsection
@section('content')
    @include('blocks.content.main')
@endsection
@section('footer')
    @include('blocks.footer.footer')
@endsection
