FROM php:fpm
RUN apt-get update && \
        apt-get install -y \
            make g++ gcc zlib1g zlib1g-dev curl libcurl4-openssl-dev libcurl4 libevent-dev libidn11-dev \
            libssl-dev git

RUN pecl install -of redis docker-php-ext-enable redis

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
        --filename=composer \
        --install-dir=/usr/local/bin && \
        echo "alias composer='composer'" >> /root/.bashrc && \
        composer

WORKDIR /var/www/html