<?php

use Illuminate\Database\Seeder;

class MpollsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('mpolls')->delete();

        \DB::table('mpolls')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Survey for 0.6£ YS Oct.',
                'created' => '2019-09-29 15:00:02',
                'modified' => '2019-12-02 03:02:09',
                'mstatus_id' => 1,
                'mtype_id' => 5,
                'starttime' => NULL,
                'endtime' => NULL,
                'price' => '0.60',
                'description' => 'Survey for £0.6  ',
                'click' => 22067,
                'repeatable' => 1,
                'country_id' => 21,
                'length' => '',
                'survlimit' => NULL,
                'prescreener' => '',
                'singleLink' => 'http://www.your-surveys.com/?si=488&ssi=[SUB]',
                'filename' => '',
                'key' => NULL,
                'incabinet' => 1,
                'cab_link' => 'https://link.luxsurveys.com/mpolls/poll/XXX',
                'cab_price' => '0.6£',
                'completes' => 3233,
                'overquotas' => 0,
                'screenout' => 0,
                'mail_id' => 32,
                'check_geo' => 1,
                'customer_id' => 8,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Federated Oct.',
                'created' => '2019-09-29 16:46:52',
                'modified' => '2019-11-20 02:23:58',
                'mstatus_id' => 1,
                'mtype_id' => 6,
                'starttime' => NULL,
                'endtime' => NULL,
                'price' => '0.80',
                'description' => 'Survey router up to £0.8 F ',
                'click' => 13022,
                'repeatable' => 1,
                'country_id' => 21,
                'length' => '',
                'survlimit' => NULL,
                'prescreener' => '',
                'singleLink' => 'https://www.samplicio.us/s/default.aspx?pid=[SUB]',
                'filename' => '78_mlink.csv',
                'key' => NULL,
                'incabinet' => 1,
                'cab_link' => 'https://link.luxsurveys.com/mpolls/poll/XXX',
                'cab_price' => 'up to £0.8',
                'completes' => 4328,
                'overquotas' => 0,
                'screenout' => 2448,
                'mail_id' => 33,
                'check_geo' => 1,
                'customer_id' => 16,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'CINT Oct.',
                'created' => '2019-09-29 16:51:29',
                'modified' => '2019-11-20 02:23:03',
                'mstatus_id' => 1,
                'mtype_id' => 3,
                'starttime' => NULL,
                'endtime' => NULL,
                'price' => '0.85',
                'description' => 'Survey up to £0.85',
                'click' => 6689,
                'repeatable' => 1,
                'country_id' => 21,
                'length' => '',
                'survlimit' => NULL,
                'prescreener' => '',
                'singleLink' => NULL,
                'filename' => '',
                'key' => NULL,
                'incabinet' => 1,
                'cab_link' => 'https://link.luxsurveys.com/mpolls/cpoll/XXX',
                'cab_price' => 'up to £0.85',
                'completes' => 0,
                'overquotas' => 0,
                'screenout' => 0,
                'mail_id' => 33,
                'check_geo' => 1,
                'customer_id' => 3,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Dalia GB Speak UP',
                'created' => '2019-10-15 23:48:52',
                'modified' => '2019-11-20 02:22:49',
                'mstatus_id' => 1,
                'mtype_id' => 2,
                'starttime' => NULL,
                'endtime' => NULL,
                'price' => '0.65',
                'description' => 'SpeakUP Surveys up to £0.65  ',
                'click' => 11460,
                'repeatable' => 1,
                'country_id' => 21,
                'length' => '',
                'survlimit' => NULL,
                'prescreener' => '',
                'singleLink' => 'http://link.luxsurveys.com/daliaoffers/rpoll/[SUB]',
                'filename' => '',
                'key' => NULL,
                'incabinet' => 1,
                'cab_link' => 'https://link.luxsurveys.com/mpolls/poll/XXX',
                'cab_price' => 'up to £0.65',
                'completes' => 0,
                'overquotas' => 0,
                'screenout' => 0,
                'mail_id' => 33,
                'check_geo' => 1,
                'customer_id' => 2,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Survey for 0.45£ Toluna Oct.  ',
                'created' => '2019-10-25 21:47:17',
                'modified' => '2019-12-04 20:23:20',
                'mstatus_id' => 1,
                'mtype_id' => 2,
                'starttime' => NULL,
                'endtime' => NULL,
                'price' => '0.60',
                'description' => 'Survey for £0.45',
                'click' => 9534,
                'repeatable' => 1,
                'country_id' => 21,
                'length' => '',
                'survlimit' => NULL,
                'prescreener' => '',
                'singleLink' => 'http://trk.thinkaction.com/?a=70010018&c=60&s1=[SUB]',
                'filename' => '',
                'key' => NULL,
                'incabinet' => 1,
                'cab_link' => 'https://link.luxsurveys.com/mpolls/poll/XXX',
                'cab_price' => '0.6£',
                'completes' => 2,
                'overquotas' => 0,
                'screenout' => 0,
                'mail_id' => 32,
                'check_geo' => 1,
                'customer_id' => 11,
            ),
        ));


    }
}
