version: "3.7"
services:
  webserver:
    image: nginx:latest
    ports:
      - "8089:80"
    volumes:
      - ./html/:/var/www/html
      - ./.docker/nginx/mysite.local.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./.docker/php
    volumes:
      - ./html/:/var/www/html
    links:
      - mysql
      - memcached

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 127.0.0.2:8001:3306
    volumes:
      - ./.docker/mysql/my.cnf:/etc/my.cnf
      - ./.docker/mysql/db:/var/lib/mysql

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"