version: '3.1'

services:
  nginx:
    image: nginx
    ports:
      - "${FORWARD_NGINX_HTTP_PORT}:80"
    volumes:
      - ./public:/app/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - .:/app
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  mysql:
    image: mysql:8
    ports:
      - "${FORWARD_MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:5
    ports:
      - "${FORWARD_REDIS_PORT}:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
