version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "801:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
      - socket:/var/run
    links:
      - php

  php:
    build: ./docker/php/
    container_name: laravel_php
    volumes:
      - ./src:/var/www/html
      - ./php.www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - socket:/var/run

volumes:
  socket: