version: "3.7"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./mysite.local.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: hb:php-sockets
    volumes:
      - ./code:/code
    links:
      - mysql
      - memcached
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./db:/var/lib/mysql
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"