<?php
return [
    'create' => 'Create Podcast',
    'no_podcasts' => 'No podcasts',
    'latest_episode' => 'Latest Episode',
    'new_podcast' => 'New Podcast',
    'to_list' => 'To all podcasts list',
    'name' => [
        'label' => 'Podcast Title',
    ],
    'description' => [
        'label' => 'Description',
    ],
    'category_itunes_id' => [
        'label' => 'iTunes Category',
        'title' => 'Choose the most accurate cateogry for your show, to be indexed by iTunes.',
    ],
    'author' => [
        'label' => 'Author',
        'title' => 'Name of the podcast\'s creator. Could also be your company name. Will be shown in podcast players, generally under the show title.',
    ],
    'copyright' => [
        'label' => 'Copyright',
    ],
    'keywords' => [
        'label' => 'Keywords or Tags (separated by coma)',
    ],
    'episode_name_template' => [
        'label' => 'Episode Title Template',
        'title' => 'Template for default autogenerated episode title. Usefull if you put episode number or show title in the episode title. Use {no} for episode number.',
    ],
    'show_notes_footer' => [
        'label' => 'Default Show Notes',
        'title' => 'This text will be added at the and of episode\'s show notes. Usually a set of links on podcast\'s website and social media.',
    ],
    'website' => [
        'label' => 'Website',
        'title' => 'Will be listed in iTunes and other podcast players as the "Podcast Website."',
    ],
    'save' => 'Save Podcast',
    'save_success' => 'Podcast has been saved',
    'delete' => 'Delete Podcast',
    'delete_confirmation' => 'Are you sure to delete podcast :name?',
];
