version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/

  mysql:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./www:/var/www

  memcached:
    image: memcached:latest