<?php

namespace Tests\Feature;

use App\Models\Business;
use App\Models\User;
use App\Models\UserRole;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Traits\UserActingAs;

/**
 * Class RecordControllerTest
 * @package Tests\Feature
 * @group RecordController
 */
class RecordControllerTest extends TestHelper
{
    use RefreshDatabase;
    use UserActingAs;

    const TABLE_NAME = 'records';

    /**
     * @var Business
     */
    private $business;
    /**
     * @var User
     */
    private $user;

    /**
     * Главная страница
     */
    public function testIndexView()
    {
        $this->getBusiness($this->user);

        $response = $this->get(route('record.index'));

        $response->assertStatus(200);
    }

    /**
     * Проверка статуса при переходе на страницу без созданного бизнеса
     */
    public function testErrorIndexWithoutBusiness()
    {
        $response = $this->get(route('record.index'));

        $response->assertStatus(403);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userActingAs();
    }
}
